name: Build

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag go-with-actions:${{steps.vars.outputs.tag}}
