name: Build

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: gotwithactions:latest
          # maximum cache
          cache-from: type=registry,ref=gotwithactions:buildcache
          cache-to: type=registry,ref=gotwithactions:buildcache,mode=max
          # minimum cache
          #cache-from: type=registry,ref=gotwithactions:latest
          #cache-to: type=inline

          #cache-from: type=local,src=/tmp/.buildx-cache
          #cache-to: type=local,dest=/tmp/.buildx-cache-new

      #- name: Move cache
      #  run: |
      #    rm -rf /tmp/.buildx-cache
      #    mv /tmp/.buildx-cache-new /tmp/.buildx-cache
